;def lcd
;whole micro port use for LCD

_dwukropek	equ	b'00111010'
_puste		equ	b'00100000'
_kropka		equ	b'00101110'
_stopni		equ	b'11011111'
_minus		equ	0x2d
_plus		equ	0x2b

_procent        equ     0x25
_star		equ	0x2a
_up		equ	b'01011110'
_przecinek	equ	0x2c
_mniejszosci      equ      0x3c
_wiekszosci       equ      0x3e
_linia_pionowa    equ         0x7c


linia_pierwsza	equ	0x80
linia_gorna	equ	0x80

linia_dolna	equ	0xc0
linia_druga	equ	0xc0

linia_trzecia	equ	0x90
linia_czwarta	equ	0xd0
;

